language: python
python: 3.6
install:
  - pip install -r requirements.txt
env:
  global:
    - TWITTER_ACCESS_TOKEN_KEY=YOUR_ACCESS_TOKEN_KEY
    - TWITTER_ACCESS_TOKEN_SECRET=YOUR_ACCESS_TOKEN_SECRET
    - TWITTER_CONSUMER_KEY=YOUR_CONSUMER_KEY
    - TWITTER_CONSUMER_SECRET=YOUR_CONSUMER_SECRET
script:
  - python -m unittest discover tests
