version: "3"
services:
  mongo:
    ports:
      - 27017:27017

  rabbitmq:
    ports:
      - 5672:5672

  web:
    ports:
      - 80:5000
    env_file:
      - .env

  worker:
    volumes:
      - ./data:/usr/src/app/data
      - ./rosie:/usr/src/app/rosie
      - ./tests:/usr/src/app/tests
      - ./whistleblower:/usr/src/app/whistleblower
