version: "3"
services:
  mongo:
    image: mongo:3.5.9
    restart: always

  rabbitmq:
    image: rabbitmq:3.6.10
    restart: always

  web:
    build: web
    restart: always
    ports:
      - 80:5000
    depends_on:
      - mongo
    environment:
      - FLASK_APP=server.py
      - MONGO_DATABASE=whistleblower
      - MONGO_URL=mongodb://mongo:27017/

  worker:
    build: .
    command: celery -A whistleblower.tasks worker -B
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env
    environment:
      - CLOUDAMQP_URL=pyamqp://guest:guest@rabbitmq:5672//
      - MONGO_DATABASE=whistleblower
      - MONGO_URL=mongodb://mongo:27017/
